import { mkdir, mkdtemp, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import PptxGenJS from "pptxgenjs";

import { BuildError, failure, readJson, sha256Bytes, sha256File, success } from "./build_common.mjs";
import { buildSlideIntoPresentation } from "./shared/ppt/build_slide_into_presentation.mjs";
import { normalizePptx } from "./shared/ppt/normalize_pptx.mjs";
import { DIMENSIONS, resolveReconstructionAssets, specToLayout } from "./shared/ppt/reconstruction_layout.mjs";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url)); const COMPONENT = "build_reconstruction_deck";

function parse(argv) { const allowed = new Set(["manifest","reconstruction-root","asset-manifest","evidence-root","output","report","python","schema-dir"]); const values={}; for(let i=0;i<argv.length;i+=2){const option=argv[i],value=argv[i+1];if(!option?.startsWith("--")||value===undefined||value.startsWith("--"))throw new BuildError(`invalid CLI argument near ${option??"<end>"}`,{exitCode:2,category:"cli_error"});const name=option.slice(2);if(!allowed.has(name)||Object.hasOwn(values,name))throw new BuildError(`unknown or duplicate option: ${option}`,{exitCode:2,category:"cli_error"});values[name]=value;}for(const name of ["manifest","reconstruction-root","asset-manifest","evidence-root","output","report"])if(!values[name])throw new BuildError(`missing --${name}`,{exitCode:2,category:"cli_error"});return values; }
function validate(kind,input,python,schemaDir){const args=[path.join(SCRIPT_DIR,"validate_spec.py"),`--${kind.replaceAll("_","-")}`,input];if(schemaDir)args.push("--schema-dir",schemaDir);const run=spawnSync(python,args,{windowsHide:true,encoding:"utf8"});if(run.status!==0)throw new BuildError(`contract validation failed: ${run.stdout||run.stderr}`,{category:"contract_error",target:input});}
async function assertOutput(value){try{await stat(value);throw new BuildError("output already exists",{category:"output_collision",target:value});}catch(error){if(error instanceof BuildError)throw error;if(error.code!=="ENOENT")throw error;}}
async function safeSpec(root,relative){if(relative.includes("\\")||relative.split("/").includes(".."))throw new BuildError("unsafe spec path",{category:"path_escape",target:relative});const resolved=path.resolve(root,...relative.split("/"));const rel=path.relative(path.resolve(root),resolved);if(!rel||rel.startsWith("..")||path.isAbsolute(rel))throw new BuildError("spec path escapes reconstruction root",{category:"path_escape",target:relative});return resolved;}

export async function buildDeck(args){const python=args.python??process.env.IVT_PYTHON??"python";validate("reconstruction_manifest",args.manifest,python,args["schema-dir"]);validate("reconstruction_asset_manifest",args["asset-manifest"],python,args["schema-dir"]);await assertOutput(args.output);await assertOutput(args.report);const manifest=await readJson(args.manifest),assetManifest=await readJson(args["asset-manifest"]);if(manifest.deck_id!==assetManifest.deck_id)throw new BuildError("manifest deck mismatch",{category:"authority_mismatch"});const specs=[];for(const entry of manifest.slides){const specPath=await safeSpec(args["reconstruction-root"],entry.spec_path);validate("visual_reconstruction_spec",specPath,python,args["schema-dir"]);const spec=await readJson(specPath);if(spec.deck_id!==manifest.deck_id||spec.slide_id!==entry.slide_id||spec.order!==entry.order||await sha256File(specPath)!==entry.spec_sha256)throw new BuildError("page spec manifest binding failed",{category:"authority_mismatch",target:entry.slide_id});specs.push(spec);}const ratios=new Set(specs.map((spec)=>spec.output_ratio));if(ratios.size!==1)throw new BuildError("all deck pages must use one output ratio",{category:"ratio_mismatch"});const dimensions=DIMENSIONS[specs[0].output_ratio],assets=await resolveReconstructionAssets(assetManifest,args["evidence-root"]);const pptx=new PptxGenJS();pptx.defineLayout({name:"P4_DECK",width:dimensions.width_in,height:dimensions.height_in});pptx.layout="P4_DECK";pptx.author="Content to Editable PPT Skill";pptx.title=`${manifest.deck_id} reconstruction candidate`;pptx.subject="P4 non-deliverable candidate deck";pptx.company="";pptx.revision="1";for(const spec of specs){const slide=pptx.addSlide();await buildSlideIntoPresentation({pptx,slide,layout:specToLayout(spec),assets});}const raw=await pptx.write({outputType:"nodebuffer",compression:true});const bytes=await normalizePptx(Buffer.from(raw),specs.length);const report={schema_version:"1.0",artifact_type:"candidate_deck_report",deck_id:manifest.deck_id,reconstruction_manifest_sha256:await sha256File(args.manifest),candidate_pptx_path:path.basename(args.output),candidate_pptx_sha256:sha256Bytes(bytes),slide_count:specs.length,slide_order:specs.map((spec)=>spec.slide_id),delivery_forbidden:true,status:"built"};await mkdir(path.dirname(path.resolve(args.output)),{recursive:true});const stage=await mkdtemp(path.join(path.dirname(path.resolve(args.output)),".p4-deck-"));try{const stagedPptx=path.join(stage,path.basename(args.output)),stagedReport=path.join(stage,path.basename(args.report));await writeFile(stagedPptx,bytes);await writeFile(stagedReport,`${JSON.stringify(report,null,2)}\n`);validate("candidate_deck_report",stagedReport,python,args["schema-dir"]);await rename(stagedPptx,args.output);await rename(stagedReport,args.report);}finally{await rm(stage,{recursive:true,force:true});}return report;}
async function main(){let args;try{args=parse(process.argv.slice(2));const report=await buildDeck(args);console.log(JSON.stringify(success(COMPONENT,{output:path.resolve(args.output),report:path.resolve(args.report),pptx_sha256:report.candidate_pptx_sha256},"p4",1)));return 0;}catch(error){console.log(JSON.stringify(failure(COMPONENT,error,"p4",1)));return error instanceof BuildError?error.exitCode:70;}}
if(path.resolve(process.argv[1]??"")===fileURLToPath(import.meta.url))process.exitCode=await main();
