from __future__ import annotations
import json,os,subprocess,sys,tempfile,unittest,zipfile
from pathlib import Path
from PIL import Image,ImageDraw

ROOT=Path(__file__).resolve().parents[2];SCRIPTS=ROOT/"content-to-editable-ppt"/"scripts";SCHEMAS=ROOT/"content-to-editable-ppt"/"schemas"
sys.path.insert(0,str(SCRIPTS))
from canonical_artifact import canonical_sha256
from schema_utils import validate_schema
from tests.runtime.test_p3_design_preview_contracts import element_map,package,H
from design_preview_contract import validate_element_map

def write(path:Path,value:dict):path.write_text(json.dumps(value,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
class PreviewBuilderTests(unittest.TestCase):
    def test_builder_creates_native_chart_text_shape_and_background(self):
        with tempfile.TemporaryDirectory() as tmp:
            root=Path(tmp);assets=root/"assets";assets.mkdir();raw=assets/"raw.png";Image.new("RGB",(1600,900),"white").save(raw);import hashlib;digest=hashlib.sha256(raw.read_bytes()).hexdigest()
            request={"schema_version":"1.3","task_id":"preview","topic":"Preview","source_image":"source.png","output_ratio":"16:9","typography_interaction":"default","typography":{"title_font":"Microsoft YaHei","title_size_pt":30,"body_font":"Microsoft YaHei","body_size_pt":18},"editability_policy":"text-and-structure","user_requirements":[],"review_policy":{"max_iterations":1,"pass_score":90,"warning_floor_score":80,"min_content_accuracy":100,"required_editability_score":100,"critical_policy":"by_recoverability"}};write(root/"request.json",request);(root/"source.png").write_bytes(raw.read_bytes())
            manifest={"schema_version":"1.3","assets":[{"id":"RAW","type":"png","path":"assets/raw.png","source":"agent-generated","width_px":1600,"height_px":900,"size_bytes":raw.stat().st_size,"sha256":digest,"recolorable":False,"contains_text":False,"text_editability_exempt":False,"security_status":"passed"}]};write(root/"asset_manifest.json",manifest)
            layout={"schema_version":"1.3","request":"request.json","source":{"image":"source.png","width_px":1600,"height_px":900},"slide":{"width_in":13.333,"height_in":7.5,"background":"#FFFFFF"},"metadata":{"topic":"Preview","iteration":1,"typography_interaction":"default"},"asset_manifest":"asset_manifest.json","styles":{},"elements":[{"id":"raw","type":"image","x":0,"y":0,"w":13.333,"h":7.5,"z_index":0,"editable":False,"asset_id":"RAW","fit":"stretch","preserve_aspect_ratio":False,"contains_text":False,"alt_text":"Preview-only raw layer"},{"id":"card","type":"shape","x":0.6,"y":1.5,"w":4,"h":2.5,"z_index":5,"editable":True,"shape":"roundRect","fill":{"color":"#F2F5FA"},"line":{"color":"#2457C5","width_pt":1}},{"id":"title","type":"text","x":0.7,"y":0.4,"w":6,"h":0.8,"z_index":20,"editable":True,"text":"正式标题","font_face":"Microsoft YaHei","font_size_pt":30,"color":"#111111","bold":True,"content_ref":"S01-TITLE"},{"id":"chart","type":"chart","x":7,"y":1.5,"w":5,"h":4,"z_index":15,"editable":True,"chart_type":"vertical_bar","categories":["A","B"],"series":[{"name":"系列","values":[10,20]}],"value_scale":1,"show_legend":True,"show_value":True,"number_format":"0","color_tokens":["2457C5"]}]};write(root/"layout.json",layout)
            node=os.environ.get("P3_TEST_NODE","node");cmd=[node,str(SCRIPTS/"build_slide.mjs"),"--iteration-dir",str(root),"--layout",str(root/"layout.json"),"--asset-manifest",str(root/"asset_manifest.json"),"--asset-dir",str(assets),"--output",str(root/"preview.pptx"),"--build-summary",str(root/"summary.json"),"--python",sys.executable,"--run-id","preview","--iteration","1"]
            done=subprocess.run(cmd,cwd=ROOT,capture_output=True,text=True);self.assertEqual(done.returncode,0,done.stdout+done.stderr);self.assertTrue((root/"preview.pptx").is_file());self.assertEqual(json.loads((root/"summary.json").read_text())["built_element_count"],4)
            with zipfile.ZipFile(root/"preview.pptx") as archive:self.assertTrue(any(name.startswith("ppt/charts/chart") for name in archive.namelist()))
            mapping=element_map();write(root/"map.json",mapping);compat=validate_element_map(mapping,package());write(root/"compat.json",compat);finalized=subprocess.run([sys.executable,str(SCRIPTS/"finalize_preview_build.py"),"--deck-id","D01","--slide-id","S01","--element-map",str(root/"map.json"),"--compatibility-report",str(root/"compat.json"),"--layout",str(root/"layout.json"),"--asset-manifest",str(root/"asset_manifest.json"),"--preview-pptx",str(root/"preview.pptx"),"--output",str(root/"preview-build-report.json")],capture_output=True,text=True);self.assertEqual(finalized.returncode,0,finalized.stdout+finalized.stderr);self.assertTrue(json.loads((root/"preview-build-report.json").read_text())["delivery_forbidden"])
            if os.environ.get("P3_PREVIEW_COM_SMOKE")=="1":
                rendered=subprocess.run([sys.executable,str(SCRIPTS/"render_ppt.py"),"--input",str(root/"preview.pptx"),"--layout",str(root/"layout.json"),"--output",str(root/"preview.png"),"--report",str(root/"render-report.json"),"--renderer","powerpoint","--run-id","p3-preview","--iteration","1"],capture_output=True,text=True);self.assertEqual(rendered.returncode,0,rendered.stdout+rendered.stderr);self.assertTrue((root/"preview.png").is_file())
    def test_provisional_foreground_extraction(self):
        with tempfile.TemporaryDirectory() as tmp:
            root=Path(tmp);raw=root/"raw.png";image=Image.new("RGB",(400,300),"white");draw=ImageDraw.Draw(image);draw.ellipse((120,60,280,240),fill="blue");image.save(raw);mapping=element_map();mapping["elements"].append({"element_id":"GEN-S01-FG01","source_ref":"S01-V01","element_owner":"generated_visual_layer","reconstruction_class":"generated_foreground","editable_required":False,"fidelity_priority":"major","p4_strategy":"extract_from_raw_layer","normalized_bbox":{"x":2500,"y":1500,"w":5000,"h":7000},"z_index":30,"relationship_refs":["EL-S01-TITLE"]});write(root/"map.json",mapping)
            done=subprocess.run([sys.executable,str(SCRIPTS/"extract_provisional_visual.py"),"--raw-layer",str(raw),"--element-map",str(root/"map.json"),"--element-id","GEN-S01-FG01","--output",str(root/"fg.png"),"--record",str(root/"record.json")],capture_output=True,text=True);self.assertEqual(done.returncode,0,done.stdout+done.stderr);record=json.loads((root/"record.json").read_text());self.assertEqual(record["background_separation"],"transparent")
if __name__=="__main__":unittest.main()
